FROM maven:3.9.9-eclipse-temurin-17 AS build
WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN mvn -q -DskipTests=false clean verify

FROM eclipse-temurin:17-jre
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar
EXPOSE 8081
ENV TNS_ADMIN=/app/wallet
ENTRYPOINT ["java","-Doracle.net.tns_admin=/app/wallet","-jar","/app/app.jar"]
